[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.13.0"
futures-util = "0.3"
clap = { version = "3.1.17", features = ["derive"] }
tokio = { version= "1.19.2", features=["full"] }
